version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains AirBnB listings.
    columns:

      - name: listing_id
        description: Primary key for the listings.
        tests:
          - unique
          - not_null

      - name: host_id
        description: Foreign key to the dim_hosts_cleansed table.
        tests:
          - not_null
          - relationships: # host_id should have a key in dim_hosts_cleansed 
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: Type of room.
        tests:
        - accepted_values:
            values: 
              - 'Entire home/apt'
              - 'Private room'
              - 'Shared room'
              - 'Hotel room'
      
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        tests:
          - positive_values

  - name: dim_listings_w_hosts
    description: Cleansed table which contains AirBnB listings with hosts.
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
    columns:

      - name: price
        description: Price of the listing.
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn

  - name: dim_hosts_cleansed
    description: Cleansed table which contains AirBnB hosts.
    columns:

      - name: host_id
        description: Primary key for the hosts.
        tests:
          - unique
          - not_null

      - name: host_name
        description: Name of the hosts.
        tests:
          - not_null

      - name: is_superhost
        description: Defines whether the host is a superhost.
        tests:
          - accepted_values:
              values:
                - 't'
                - 'f'